import crypto from 'crypto'; import { Router } from 'express'; import { env } from './config.js'; import { supabase } from './db.js'; import { avatarUpload } from './upload.js'; import { profileSchema } from '../shared/profileSchema.js';
const router=Router();
async function getProfile(){const {data,error}=await supabase.from('task26_profiles').select('*').order('created_at',{ascending:true}).limit(1).single();if(error)throw error;return data}
async function withAvatar(p){if(!p.avatar_path)return {...p,avatar_url:null};const {data,error}=await supabase.storage.from(env.avatarBucket).createSignedUrl(p.avatar_path,3600);return {...p,avatar_url:error?null:data.signedUrl}}
router.get('/',async(req,res,next)=>{try{res.json({success:true,profile:await withAvatar(await getProfile())})}catch(e){next(e)}});
router.put('/',async(req,res,next)=>{try{const parsed=profileSchema.safeParse(req.body);if(!parsed.success)return res.status(422).json({success:false,message:'Please correct the highlighted fields.',errors:parsed.error.issues.reduce((a,i)=>{a[i.path[0]||'form']??=i.message;return a},{})});const p=await getProfile(),d=parsed.data;const {data,error}=await supabase.from('task26_profiles').update({full_name:d.fullName,email:d.email,role:d.role,company:d.company,phone:d.phone||null,location:d.location||null,website:d.website||null,bio:d.bio||null,updated_at:new Date().toISOString()}).eq('id',p.id).select('*').single();if(error)throw error;res.json({success:true,message:'Profile updated successfully.',profile:await withAvatar(data)})}catch(e){next(e)}});
router.post('/avatar',avatarUpload.single('avatar'),async(req,res,next)=>{try{if(!req.file)return res.status(400).json({success:false,message:'Choose an avatar first.'});const p=await getProfile();if(p.avatar_path)await supabase.storage.from(env.avatarBucket).remove([p.avatar_path]);const ext=req.file.mimetype==='image/png'?'png':req.file.mimetype==='image/webp'?'webp':'jpg';const path=`${p.id}/${crypto.randomUUID()}.${ext}`;const {error:upErr}=await supabase.storage.from(env.avatarBucket).upload(path,req.file.buffer,{contentType:req.file.mimetype});if(upErr)throw upErr;const {data,error}=await supabase.from('task26_profiles').update({avatar_path:path,updated_at:new Date().toISOString()}).eq('id',p.id).select('*').single();if(error)throw error;res.json({success:true,message:'Avatar updated successfully.',profile:await withAvatar(data)})}catch(e){next(e)}});
router.delete('/avatar',async(req,res,next)=>{try{const p=await getProfile();if(p.avatar_path){const {error:r}=await supabase.storage.from(env.avatarBucket).remove([p.avatar_path]);if(r)throw r}const {data,error}=await supabase.from('task26_profiles').update({avatar_path:null,updated_at:new Date().toISOString()}).eq('id',p.id).select('*').single();if(error)throw error;res.json({success:true,message:'Avatar removed.',profile:await withAvatar(data)})}catch(e){next(e)}});
export default router;
