create table products(
 id bigint generated by default as identity primary key,
 name text not null,
 price numeric not null,
 category text,
 created_at timestamp with time zone default now()
);

insert into products(name,price,category)
values
('Laptop',800,'Electronics'),
('Phone',1200,'Electronics');
