-- Pulseboard activity schema
create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  username text not null,
  action text not null check (action in ('Logged in', 'Logged out', 'Uploaded file', 'Updated profile', 'System action')),
  details text default '',
  created_at timestamptz not null default now()
);

alter table public.activities enable row level security;

-- API reads and inserts use the server key. This policy allows the browser's
-- anon key to receive Realtime row events after enabling the table below.
drop policy if exists "Allow activity reads" on public.activities;
create policy "Allow activity reads" on public.activities for select using (true);

do $$ begin
  alter publication supabase_realtime add table public.activities;
exception when duplicate_object then null;
end $$;

-- Sample activity inserts
insert into public.activities (username, action, details) values
('Aisha Khan', 'Logged in', 'Web session started'),
('Marcus Lee', 'Uploaded file', 'Q3-report.pdf'),
('Nora Patel', 'Updated profile', 'Changed notification preferences'),
('System', 'System action', 'Nightly backup completed');
