import React,{useEffect,useMemo,useRef,useState} from 'react';
import { BriefcaseBusiness,Building2,Camera,CheckCircle2,CircleAlert,Globe2,LoaderCircle,Mail,MapPin,Phone,Save,Settings,ShieldCheck,Sparkles,Trash2,UserRound,X } from 'lucide-react';
import { useForm } from 'react-hook-form'; import { zodResolver } from '@hookform/resolvers/zod'; import { profileSchema } from '../shared/profileSchema.js'; import { fetchProfile,removeAvatar,updateProfile,uploadAvatar } from './api.js';
export default function App(){
 const fileRef=useRef(null),[profile,setProfile]=useState(null),[loading,setLoading]=useState(true),[avatarBusy,setAvatarBusy]=useState(false),[toast,setToast]=useState(null);
 const {register,handleSubmit,reset,watch,setError,formState:{errors,isDirty,isSubmitting}}=useForm({resolver:zodResolver(profileSchema),mode:'onChange',defaultValues:{fullName:'',email:'',role:'',company:'',phone:'',location:'',website:'',bio:''}});
 const values=watch();
 const hydrate=p=>{setProfile(p);reset({fullName:p.full_name||'',email:p.email||'',role:p.role||'',company:p.company||'',phone:p.phone||'',location:p.location||'',website:p.website||'',bio:p.bio||''})};
 useEffect(()=>{fetchProfile().then(d=>hydrate(d.profile)).catch(e=>setToast({tone:'error',message:e.message})).finally(()=>setLoading(false))},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(null),3500);return()=>clearTimeout(t)},[toast]);
 const completion=useMemo(()=>{const keys=['fullName','email','role','company','phone','location','website','bio'];let n=keys.filter(k=>String(values[k]||'').trim()).length;if(profile?.avatar_url)n++;return Math.round(n/9*100)},[values,profile]);
 async function save(data){try{const r=await updateProfile(data);hydrate(r.profile);setToast({tone:'success',message:r.message})}catch(e){Object.entries(e.fieldErrors||{}).forEach(([f,m])=>setError(f,{type:'server',message:m}));setToast({tone:'error',message:e.message})}}
 function cancel(){hydrate(profile);setToast({tone:'neutral',message:'Unsaved changes discarded.'})}
 async function onAvatar(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;setAvatarBusy(true);try{const r=await uploadAvatar(file);hydrate(r.profile);setToast({tone:'success',message:r.message})}catch(err){setToast({tone:'error',message:err.message})}finally{setAvatarBusy(false)}}
 async function delAvatar(){setAvatarBusy(true);try{const r=await removeAvatar();hydrate(r.profile);setToast({tone:'success',message:r.message})}catch(err){setToast({tone:'error',message:err.message})}finally{setAvatarBusy(false)}}
 if(loading)return <div className="loading"><LoaderCircle className="spin"/>Loading profile...</div>;
 if(!profile)return <div className="loading error"><CircleAlert/>Unable to load profile.</div>;
 const initials=profile.full_name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();
 return <div className="page"><div className="orb one"/><div className="orb two"/><div className="gridbg"/>
  <aside className="sidebar"><div className="brand"><span><UserRound size={22}/></span><div><b>ProfileHub</b><small>Identity Workspace</small></div></div><nav><button className="active"><UserRound size={17}/>My profile</button><button disabled><Settings size={17}/>Preferences</button><button disabled><ShieldCheck size={17}/>Security</button></nav><div className="sidecard"><Sparkles size={17}/><b>Profile management</b><p>Edit identity data, avatar storage and keep Supabase synchronized.</p></div><div className="task">TASK 26<strong>Profile Management</strong></div></aside>
  <main className="workspace"><header><div><small>ACCOUNT / PROFILE</small><h1>Your professional <em>identity.</em></h1><p>Manage personal information, profile strength and secure avatar storage from one polished workspace.</p></div><div className={isDirty?'savestate dirty':'savestate'}><i/>{isDirty?'Unsaved changes':'All changes saved'}</div></header>
  <section className="layout"><aside className="profilecard"><div className="cover"/><div className="avatarwrap"><div className="avatar">{profile.avatar_url?<img src={profile.avatar_url} alt="Avatar"/>:<span>{initials}</span>}{avatarBusy&&<div className="avatarbusy"><LoaderCircle className="spin"/></div>}</div><button className="cambtn" onClick={()=>fileRef.current?.click()} disabled={avatarBusy}><Camera size={15}/></button><input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={onAvatar}/></div><h2>{profile.full_name}</h2><p className="role">{profile.role}</p><div className="company"><Building2 size={14}/>{profile.company}</div><div className="completion"><div className="ring" style={{'--value':`${completion*3.6}deg`}}><span><b>{completion}%</b><small>complete</small></span></div><div><b>Profile strength</b><p>Complete more fields to improve your profile.</p></div></div><div className="avataractions"><button onClick={()=>fileRef.current?.click()} disabled={avatarBusy}><Camera size={14}/>Change photo</button>{profile.avatar_path&&<button className="danger" onClick={delAvatar} disabled={avatarBusy}><Trash2 size={14}/>Remove</button>}</div><small className="help">JPG, PNG or WebP · max 3 MB</small></aside>
  <section className="editcard"><div className="edithead"><div><small>PROFILE DETAILS</small><h2>Personal information</h2><p>Validated on the client and API before saving.</p></div><ShieldCheck size={20}/></div><form onSubmit={handleSubmit(save)} noValidate><div className="formgrid"><Field label="Full name" icon={UserRound} error={errors.fullName?.message}><input {...register('fullName')}/></Field><Field label="Email address" icon={Mail} error={errors.email?.message}><input type="email" {...register('email')}/></Field><Field label="Professional role" icon={BriefcaseBusiness} error={errors.role?.message}><input {...register('role')}/></Field><Field label="Company" icon={Building2} error={errors.company?.message}><input {...register('company')}/></Field><Field label="Phone" icon={Phone} error={errors.phone?.message}><input {...register('phone')}/></Field><Field label="Location" icon={MapPin} error={errors.location?.message}><input {...register('location')}/></Field><Field label="Website" icon={Globe2} error={errors.website?.message} wide><input {...register('website')}/></Field><Field label="Professional bio" icon={Sparkles} error={errors.bio?.message} wide><div className="textwrap"><textarea maxLength={400} {...register('bio')}/><span>{(values.bio||'').length}/400</span></div></Field></div><div className="footer"><div className="updated"><CheckCircle2 size={15}/>Last updated {new Date(profile.updated_at).toLocaleString()}</div><div><button type="button" className="secondary" disabled={!isDirty} onClick={cancel}><X size={15}/>Cancel</button><button className="primary" disabled={!isDirty||isSubmitting}>{isSubmitting?<><LoaderCircle className="spin" size={16}/>Saving...</>:<><Save size={16}/>Save changes</>}</button></div></div></form></section></section></main>
  {toast&&<div className={`toast ${toast.tone}`}>{toast.tone==='error'?<CircleAlert size={17}/>:<CheckCircle2 size={17}/>}<span>{toast.message}</span></div>}
 </div>
}
function Field({label,icon:Icon,error,wide,children}){return <label className={`field ${error?'bad':''} ${wide?'wide':''}`}><span><Icon size={14}/>{label}</span>{children}<small>{error||' '}</small></label>}
