create extension if not exists pgcrypto;

create table if not exists public.task29_users(
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null default 'auditor',
  created_at timestamptz not null default now()
);

create table if not exists public.task29_audit_logs(
  id uuid primary key default gen_random_uuid(),
  sequence_no bigint generated by default as identity unique,
  actor_email text not null,
  actor_name text not null,
  action text not null,
  category text not null check(category in ('auth','data','access','system')),
  severity text not null check(severity in ('info','warning','critical')),
  entity_type text not null,
  entity_id text,
  message text not null,
  ip_address text,
  user_agent text,
  before_data jsonb,
  after_data jsonb,
  metadata jsonb not null default '{}'::jsonb,
  previous_hash text not null,
  event_hash text not null unique,
  created_at timestamptz not null default now()
);

create index if not exists task29_audit_created_idx on public.task29_audit_logs(created_at desc);
create index if not exists task29_audit_actor_idx on public.task29_audit_logs(actor_email);
create index if not exists task29_audit_action_idx on public.task29_audit_logs(action);
create index if not exists task29_audit_category_idx on public.task29_audit_logs(category);
create index if not exists task29_audit_severity_idx on public.task29_audit_logs(severity);

alter table public.task29_users enable row level security;
alter table public.task29_audit_logs enable row level security;

create or replace function public.task29_block_audit_mutation()
returns trigger language plpgsql as $$
begin
  raise exception 'task29_audit_logs is append-only: UPDATE/DELETE blocked';
end;
$$;

drop trigger if exists task29_no_update on public.task29_audit_logs;
create trigger task29_no_update before update on public.task29_audit_logs
for each row execute function public.task29_block_audit_mutation();

drop trigger if exists task29_no_delete on public.task29_audit_logs;
create trigger task29_no_delete before delete on public.task29_audit_logs
for each row execute function public.task29_block_audit_mutation();
