import bcrypt from 'bcryptjs';
import {userRepository} from './repositories/userRepository.js';
import {departmentRepository} from './repositories/departmentRepository.js';
import {requestRepository} from './repositories/requestRepository.js';
export async function ensureDemoData(){let admin=await userRepository.findByEmail('admin@layerdesk.dev');if(!admin)admin=await userRepository.create({full_name:'Aqsa Khan',email:'admin@layerdesk.dev',password_hash:await bcrypt.hash('Admin@12345',12),role:'admin'});let deps=await departmentRepository.list();if(!deps.length)deps=await departmentRepository.insertMany([{name:'Customer Success',code:'CS',manager_name:'Sarah Malik'},{name:'Technical Operations',code:'TECH',manager_name:'Bilal Ahmed'},{name:'Billing & Finance',code:'FIN',manager_name:'Hira Khan'},{name:'Enterprise Delivery',code:'ENT',manager_name:'Hamza Ali'}]);if(await requestRepository.count())return;const d=Object.fromEntries(deps.map(x=>[x.code,x]));const now=Date.now();await requestRepository.insertMany([
{request_number:'SR-31001',client_name:'Northstar Labs',client_email:'ops@northstar.example',subject:'Executive dashboard latency',description:'Leadership dashboard is slower than the agreed response target.',department_id:d.TECH.id,priority:'critical',status:'in_progress',sla_due_at:new Date(now+2*3600000).toISOString(),created_by:admin.id},
{request_number:'SR-31002',client_name:'Aurelia Retail',client_email:'team@aurelia.example',subject:'Monthly billing reconciliation',description:'Client requested a review of two invoice line items.',department_id:d.FIN.id,priority:'medium',status:'assigned',sla_due_at:new Date(now+48*3600000).toISOString(),created_by:admin.id},
{request_number:'SR-31003',client_name:'Vertex Capital',client_email:'delivery@vertex.example',subject:'Enterprise onboarding plan',description:'Prepare final onboarding milestones for the implementation team.',department_id:d.ENT.id,priority:'high',status:'waiting',sla_due_at:new Date(now+14*3600000).toISOString(),created_by:admin.id},
{request_number:'SR-31004',client_name:'Beacon Health',client_email:'success@beacon.example',subject:'Training session follow-up',description:'Send training resources and schedule final adoption checkpoint.',department_id:d.CS.id,priority:'low',status:'resolved',sla_due_at:new Date(now+80*3600000).toISOString(),created_by:admin.id},
{request_number:'SR-31005',client_name:'Orion Commerce',client_email:'it@orion.example',subject:'API credential rotation',description:'Coordinate secure production credential rotation.',department_id:d.TECH.id,priority:'high',status:'completed',sla_due_at:new Date(now-10*3600000).toISOString(),created_by:admin.id}
])}
