import {writeFile,mkdir,readFile} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const tab=await(await fetch('http://localhost:9223/json/new?http://localhost:5173',{method:'PUT'})).json();
const ws=new WebSocket(tab.webSocketDebuggerUrl);
await new Promise(r=>ws.addEventListener('open',r,{once:true}));
let id=0;const pending=new Map(),errors=[];
ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result)}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text)});
const cdp=(method,params={})=>new Promise((resolve,reject)=>{const seq=++id;pending.set(seq,{resolve,reject});ws.send(JSON.stringify({id:seq,method,params}))});
const evaluate=async expression=>{const r=await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value};
const settle=()=>new Promise(r=>setTimeout(r,200));
const click=async text=>{await evaluate(`(()=>{const b=[...document.querySelectorAll('button')].find(x=>x.textContent.trim()===${JSON.stringify(text)});if(!b)throw Error('Missing button: '+${JSON.stringify(text)});b.click()})()`);await settle()};
const select=async selector=>{await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);await settle()};
const field=async(name,value)=>{await evaluate(`(()=>{const el=document.querySelector('[name="${name}"]');Object.getOwnPropertyDescriptor(el.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype,'value').set.call(el,${JSON.stringify(value)});el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))})()`);await settle()};
const text=()=>evaluate('document.body.innerText');
const nav=async n=>select(`nav button:nth-child(${n})`);
await cdp('Runtime.enable');await cdp('Page.enable');await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});await new Promise(r=>setTimeout(r,1200));
const saved=await evaluate("localStorage.getItem('flowdesk-v2')");
try{
 await evaluate("localStorage.removeItem('flowdesk-v2');location.reload()");await new Promise(r=>setTimeout(r,1000));assert.match(await text(),/Welcome back, Alex/);
 await mkdir('artifacts',{recursive:true});await evaluate('document.fonts.ready');await settle();const shot=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile('artifacts/dashboard-desktop.png',Buffer.from(shot.data,'base64'));
 await click('＋ New project');for(const[n,v]of Object.entries({name:'Browser test project',client:'Test company',category:'Design',progress:'35',budget:'1500',date:'2026-12-01'}))await field(n,v);await click('Save changes');assert.match(await text(),/Browser test project/);
 await evaluate('location.reload()');await new Promise(r=>setTimeout(r,800));assert.match(await text(),/Browser test project/);
 await select('[aria-label="Edit Browser test project"]');await field('status','Completed');await click('Save changes');assert.equal(await evaluate("JSON.parse(localStorage.getItem('flowdesk-v2')).projects.find(p=>p.name==='Browser test project').progress"),100);
 await select('[aria-label="Edit Browser test project"]');await click('Delete');await click('Yes, delete');assert.doesNotMatch(await text(),/Browser test project/);
 await nav(4);await click('＋ New task');await field('name','Browser test task');await field('date','2026-12-02');await click('Save changes');await select('[aria-label="Complete Browser test task"]');assert.equal(await evaluate("JSON.parse(localStorage.getItem('flowdesk-v2')).tasks.find(t=>t.name==='Browser test task').done"),true);
 await nav(2);await click('＋ Add customer');for(const[n,v]of Object.entries({name:'Test customer',company:'Test company',email:'test@example.com'}))await field(n,v);await click('Save changes');assert.match(await text(),/test@example.com/);
 await nav(5);await click('＋ Add member');for(const[n,v]of Object.entries({name:'Test member',role:'Designer',email:'member@example.com'}))await field(n,v);await click('Save changes');assert.match(await text(),/Test member/);
 await nav(3);await evaluate(`(()=>{const el=document.querySelector('[aria-label="Search current page"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'Website');el.dispatchEvent(new Event('input',{bubbles:true}))})()`);await settle();assert.equal(await evaluate('document.querySelectorAll("tbody tr").length'),1);
 await nav(3);await evaluate(`(()=>{const el=document.querySelector('[aria-label="Filter project status"]');Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(el,'Completed');el.dispatchEvent(new Event('change',{bubbles:true}))})()`);await settle();assert.equal(await evaluate('document.querySelectorAll("tbody tr").length'),1);
 await nav(6);assert.match(await text(),/Project budget breakdown/);await evaluate(`(()=>{const el=document.querySelector('[aria-label="Chart period"]');Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(el,'Last 3 months');el.dispatchEvent(new Event('change',{bubbles:true}))})()`);await settle();assert.match(await text(),/\$104,500/);
 await nav(7);await click('Summarize project budgets ↗');assert.match(await text(),/Your project budgets total/);
 await click('⚙ Settings & preferences');await click('Edit preferences');await field('name','Jordan Smith');await click('Save changes');assert.match(await text(),/Jordan Smith/);await nav(1);assert.match(await text(),/Welcome back, Jordan/);
 await cdp('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:path.resolve('artifacts')});await click('↥ Export');await new Promise(r=>setTimeout(r,800));const exported=JSON.parse(await readFile('artifacts/flowdesk-workspace.json','utf8'));assert.equal(exported.profile.name,'Jordan Smith');
 await select('[aria-label="Notifications"]');assert.match(await text(),/Workspace activity/);await select('[aria-label="Notifications"]');
 await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await settle();assert.equal(await evaluate('document.documentElement.scrollWidth<=window.innerWidth'),true,'Mobile page should not overflow horizontally');
 await select('[aria-label="Toggle navigation"]');assert.equal(await evaluate("document.querySelector('aside').classList.contains('open')"),true);await nav(3);assert.match(await text(),/All projects/);await select('[aria-label="Toggle navigation"]');await nav(1);
 await new Promise(r=>setTimeout(r,4200));const mobile=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile('artifacts/dashboard-mobile.png',Buffer.from(mobile.data,'base64'));
 assert.deepEqual(errors,[]);console.log('PASS: project CRUD, persistence, task completion, CRM, team, search, analytics, assistant, preferences, mobile navigation and layout, no runtime errors.');
}finally{await evaluate(`localStorage.setItem('flowdesk-v2',${JSON.stringify(saved||'null')});location.reload()`);ws.close()}
